{% set name = "pick" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pick-{{ version }}.tar.gz
  sha256: 96920ebcfb9b8b6c2e50d9f211a700e5036611904169587a5a9245a645637a0d

build:
  skip: true  # [py<36 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - dataclasses >=0.8,<0.9  # [py>=36 and py<37]
    - python
    # this would unblock the windows package
    # - windows-curses >=2.2.0,<3.0.0  # [win]

test:
  imports:
    - pick
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wong2/pick
  summary: Pick an option in the terminal with a simple GUI
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wong2
